# Generated by Django 4.1.3 on 2022-11-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarcy_system', '0002_alter_organizationuser_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarcy_system.organizationuser'),
        ),
    ]
