# Generated by Django 4.1.3 on 2022-11-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarcy_system', '0004_alter_organizationuser_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='subportfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarcy_system.portfolio'),
        ),
    ]
